### ISSUE TITLE
pfx problem

### ISSUE THREAD

**Issue by Bickson** [anyfin/bankid#11]
Hi, I just get this when I try to give path to the downloaded .pfx cert?
any idea how to link to .pfx file?
```
fs.js:663
return binding.open(pathModule.toNamespacedPath(path),
ENOENT: no such file or directory, open '....pfx'
```

**Comment by kimpers** [comment]
Hi @Bickson,

Maybe you already soved this issue but just in case. You need to provide the path relative to your current work directory when executing the node application.

Example:
```
.
├── certs
│   └── test.pfx
├── src
│   └── test.js
```
starting from the working directory you would run the script with `node src/test.js` and provide the pfx path like this
```javascript
const bankid = new Bankid({
  pfx: "certs/test.pfx"
});
```

This may not be very clear from the documentation, sorry about that.

**Comment by kimpers** [comment]
I've added this explanation to the README file, hopefully this will clear up any confusion. 

Closing this issue. Feel to open another issue is you have any remaining questions.
