### ISSUE TITLE
invalidParameters

### ISSUE THREAD

**Issue by kigh143** [anyfin/bankid#33]
I have set every as documented in the readme file, it was working before but now I am getting this error invalid parameters. What could be the issue?

**Comment by a7ul** [comment]
Hi @kigh143 
could you post more details like stack trace and how you are calling the functions ? 

Its hard to debug the issue without more details.

**Comment by kigh143** [comment]
It's the only error message I get back.

**Comment by kigh143** [comment]
```
error orderRef Error: invalidParameters
    at /home/ghkatende/Desktop/MyApps/Nodejs/bankIdRelay/node_modules/bankid/lib/bankid.js:138:39
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  details: 'Invalid request'
}
```

**Comment by kigh143** [comment]
I now get this object back when I make a sign request. I don't seems to get how to go past it 
```
{
    "message": {
        "name": "BankIdError",
        "code": "alreadyInProgress",
        "details": "Order already in progress for pno"
    }
}
```

**Comment by a7ul** [comment]
```
{
    "message": {
        "name": "BankIdError",
        "code": "alreadyInProgress",
        "details": "Order already in progress for pno"
    }
}
```

For this you ll need to wait a bit till the request times out at the bankid's end

**Comment by kigh143** [comment]
Thank you @a7ul.  I am getting it quite a lot of late, how long does this take for the time. I tried implementing a cancel before a request is made, but it didnt help as well.

**Comment by ktra99** [comment]
I got the same error as @kigh143 

I solved it by using signAndCollect along with async await.

I'm using next.js api but it should work on any node platform nevertheless

Here's the following code snippet -

```
try{
	const client = new BankId.BankIdClient();
  const pno = "YYYYMMDDXXXX";
  const message = "some message displayed to the user to sign";

  const sign = await client.signAndCollect({
    endUserIp: "127.0.0.1",
    personalNumber: pno,
    userVisibleData: message,
  })

  res.status(200).json({message: sign.completionData})
}
catch(e){
  res.status(500).json({message: e.message})
}
```

I think the current code could be improved by replaceing promise chains with async await. By doing this we can essentialy remove the unnnessecary intervals and integrate our own error handler

**Comment by albingroen** [comment]
I get the same error:

```
BankIdError: invalidParameters {
  code: 'invalidParameters',
  details: 'Invalid request'
}
```

Code:

```javascript
const BankId = require("bankid");

const client = new BankId.BankIdClient();
const pno = "XXXXXXXXXXXX" // redacted for privacy;
const message = "some message displayed to the user to sign";

client
  .sign({
    endUserIp: "127.0.0.1",
    personalNumber: pno,
    userVisibleData: message,
  })
  .then(res => {
    const timer = setInterval(() => {
      const done = () => clearInterval(timer);
      client
        .collect(res.orderRef)
        .then(res => {
          if (res.status === "complete") {
            console.log(res.completionData);
            done();
          } else if (res.status === "failed") {
            throw new Error(res.hintCode);
          }
        })
        .catch(err => {
          console.error(err);
          done();
        });
    }, 1000);
  })
  .catch(console.error);
```

**Comment by keydoublen** [comment]
For people struggling with this, try using one of the main convenience methods. Here's my own implementation using request-ip, luhn and bankid combined - import fs from 'fs'
import path from 'path'
const luhn = require('luhn')
const BankId = require('bankid')
import requestIp from 'request-ip'

export default async (req, res) => {
	try{
		const dir = path.resolve('./certs/Keystore_ProvsvaretSverigeAB_20220312.p12')
		const { pno } = req.body
		const client = new BankId.BankIdClient()
		if(luhn.validate(pno.substring(2))){
      const sign = await client.authenticateAndCollect({
        personalNumber: pno,
				endUserIp: requestIp.getClientIp(req)
      })
      res.status(200).json({ success: true, data: sign.completionData })
    }
    else{
      throw Error('Ogiltigt personnummer')
    }
	}
	catch(err){
		res.status(400).json({ success: false, err: err.message })
	}
}

**Comment by pmmmwh** [comment]
Something like this should work - note that the `collect` method takes an object of parameters instead of just the `orderRef` directly.

```js
client
  .sign({
    endUserIp: "127.0.0.1",
    personalNumber: pno,
    userVisibleData: message,
  })
  .then(async res => {
    await client.collect({ orderRef: res.orderRef })
  })
  .catch(console.error);
```
