### ISSUE TITLE
Add support for Markdown formatting (userVisibleDataFormat)

### ISSUE THREAD

**Issue by fabhed** [anyfin/bankid#34]
BankID added an optional `userVisibleDataFormat` parameter to allow Markdown syntax in `userVisibleData`

Relevant documentation:
![image](https://user-images.githubusercontent.com/9154566/129348168-6c3216ee-f95f-4c4e-bd34-e1abd188906a.png)

Sign request example ([source](https://www.bankid.com/utvecklare/guider/formatera-text/formatera-text-parametrar)):
```json
{
"personalNumber":"190000000000",
"endUserIp": "194.168.2.25",
"userVisibleData": "IFRoaXMgaXMgYSBzYW1wbGUgdGV4dCB0byBiZSBzaWduZWQ=",
"userVisibleDataFormat": "simpleMarkdownV1"
}
```

**Comment by a7ul** [comment]
Awesome! @minifjurt123  could you help raise a pr for this ?

**Comment by jeham** [comment]
This works:

```
  const params = {personalNumber, endUserIp, userVisibleData, userVisibleDataFormat: 'simpleMarkdownV1'}
  return await bankIdClient.sign(params)
```
