### ISSUE TITLE
Stop interval-timer when error thrown

### ISSUE THREAD

**Issue by trycoon** [anyfin/bankid#50]
https://github.com/anyfin/bankid/blob/e8a2f5b1c96e153858b1bc0dfab2c0bb05ed4cdb/examples/collect.js#L21

done() should be called here too, I believe, otherwise the interval could continue after error was thrown.

**Comment by a7ul** [comment]
When an error is thrown inside the promise's then callback it would go to the next catch block right? so the error would then be logged and done() will be called there?

**Comment by trycoon** [comment]
You are absolutly right! Sorry for bothering.
