### ISSUE TITLE
QR support

### ISSUE THREAD

**Issue by swimand** [anyfin/bankid#51]
Hi, have you considered implementing support for qrStartSecrets and qrStartSecrets?

**Comment by a7ul** [comment]
Hi @swimand 
You could use the following code snippet at your end to generate qr code

```ts
import { createHmac } from "node:crypto";

type QrCache = {
  startTime: number;
  qrStartToken: string;
  qrStartSecret: string;
};
const cache = new Map<string, QrCache>();
/**
 * get the first animated qr and store important values in cache
 **/
async function startQr(
  qrStartSecret: string,
  qrStartToken: string,
  orderRef: string
) {
  const now = Date.now();
  const qrStore = { startTime: now, qrStartSecret, qrStartToken };
  cache.set(orderRef, qrStore);
  return this.generateQr({ ...qrStore, time: 0 });
}

/**
 * generate next animated qr based on time and values in cache
 **/
async function nextQr(orderRef: string) {
  const qr =  cache.get(orderRef);
  if (!qr) {
    return;
  }
  const qrTime = parseInt(`${(Date.now() - qr.startTime) / 1000}`, 10);
  return generateQr(qr.qrStartSecret, qr.qrStartToken, qrTime);
}

function generateQr(qrStartSecret: string, qrStartToken: string, time: number) {
  const qrAuthCode = createHmac("sha256", qrStartSecret)
    .update(`${time}`)
    .digest("hex");
  return `bankid.${qrStartToken}.${time}.${qrAuthCode}`;
}


```

Here 
first you would call `startQr` and subsequently call `nextQr`

The support for this doesnt exist today in the library but if you have time feel free to raise a PR

**Comment by swimand** [comment]
Brilliant, thank you for the code snippet! Will definitely help en QR code generation 👍

**Comment by trycoon** [comment]
The deadline for mandatory QR-code is drawing near, is there a complete example showing show to implement a full BankdID integration using QR-code? Or is the above code the most complete we have?
Thanks for all your work!

**Comment by swimand** [comment]
I generated a QR code on the FE instead, so i simply send the data and the other necessary items there. 
I am using this library to generate the image:

https://www.npmjs.com/package/qrcode

**Comment by fredrik** [comment]
The work on the v6 client (https://github.com/anyfin/bankid/pull/57) includes a `QrGenerator` class (see [src/qrgenerator.ts](https://github.com/anyfin/bankid/blob/master/src/qrgenerator.ts)). I believe that qualifies as "QR support" and is enough to close this issue.
