### ISSUE TITLE
Can you specify a timeout?

### ISSUE THREAD

**Issue by fredrik** [anyfin/bankid#52]
Is there a way to specify a timeout? If not, what is the default timeout if any?

I'm not seeing anything obvious whilst browsing the code other than the `REQUEST_TIMEOUT` response code, which is seemingly defined but not referenced.

We have a fairly short timeout per default of six seconds for our Lambdas and on occasion requests will take longer than that.

**Comment by pereriksson** [comment]
The `requestTimeout` error is defined by the bankid service, it is however not elaborated on further in the docs.
https://www.bankid.com/en/utvecklare/guider/teknisk-integrationsguide/graenssnittsbeskrivning/felfall

The default timeout of axios (which we are using) is 0 (no timeout).
https://github.com/axios/axios/blob/main/README.md#request-config

Perhaps try something like this?
```
const bankid = BankIdClient(options)
bankid.axios.defaults.timeout = 5000
```

**Comment by fredrik** [comment]
Thanks @pereriksson! I forgot to feedback on this, closing as solved now.
