### ISSUE TITLE
Skipping pnr to be able to use autostartToken

### ISSUE THREAD

**Issue by viktorlarsson** [anyfin/bankid#6]
In BankID relaying guidelines from version 3.1.2 you can now skip personal identification number and use the autostarttoken. This enables for example inside an app that you can open the BankID without supplying the pnr.

[bankid-relaying-party-guidelines-v3.1](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.1.pdf)

Should be able to check here if the personalNumber was not supplied.

https://github.com/anyfin/bankid/blob/ae6355df339e808401b5a00afc1969c7dff78692/src/bankid.js#L49-L52

**Comment by hyperborea** [comment]
Thanks for the PR @viktorlarsson!

We're actually already using the library internally skipping the personal identification number and it appears to work just fine even without the explicit check. Passing `undefined` should be equivalent to not setting it in the first place. Did you run into trouble on your end?

**Comment by viktorlarsson** [comment]
Right you are, I was passing an empty string and the error became incorrect personal number. But

**Comment by kimpers** [comment]
Closing this issue as it's inactive and it seems that the problem was resolved. Feel free to open another one if there are any remaning issues
