### ISSUE TITLE
Support of `userVisibleData` and `userVisibleDataFormat` to `.authenticate`?

### ISSUE THREAD

**Issue by alepek** [anyfin/bankid#69]
Hi! The [BankID api for /auth](https://www.bankid.com/utvecklare/guider/teknisk-integrationsguide/graenssnittsbeskrivning/auth) supports `userVisibleData` and `userVisibleDataFormat` to show the user some markdown when performing authentication.

As far as I can tell these parameters are not supported in this library. Do you have any plans to add support for these parameters?

**Comment by pmmmwh** [comment]
See #57

**Comment by alepek** [comment]
Hey @pmmmwh! Looking forward to that PR. However, I'm not seeing any discussion or code changes in it related to extending the `.authenticate` function. I'll see if I can create a fork/pr with the suggested changes.

**Comment by pmmmwh** [comment]
> Hey @pmmmwh! Looking forward to that PR. However, I'm not seeing any discussion or code changes in it related to extending the `.authenticate` function. I'll see if I can create a fork/pr with the suggested changes.

As I recall the two parameters are only usable for V6 - so I would assume this is within scope of that PR. Feel free to mention this there? I would think we can extend the BankIDReqeust to accept a new variant of AuthRequestV6.

**Comment by alepek** [comment]
Here's the changes I'm suggesting https://github.com/anyfin/bankid/pull/70

As I mentioned in the PR these parameters are technically already supported by the library (since the entire params object is forwarded). From what I can tell there is support for these variables for `auth` as well as sign according to https://www.bankid.com/utvecklare/guider/teknisk-integrationsguide/graenssnittsbeskrivning/auth

**Comment by alepek** [comment]
> As I recall the two parameters are only usable for V6 - so I would assume this is within scope of that PR. Feel free to mention this there? I would think we can extend the BankIDReqeust to accept a new variant of AuthRequestV6.

Sorry, I missed this response. It's unfortunately not possible to download the API definitions for 5.1 from the BankID docs atm, but my impression from reading the changelog was that these variables were supported in V5.1 as well since they were not listed in the changes for V6. If that is not the case this issue and related PR can be closed and I can make a request in the V6 PR!
