### ISSUE TITLE
Node.js v22 is now long-term support

### ISSUE THREAD

**Issue by oddball** [anyfin/bankid#88]
In https://github.com/anyfin/bankid/blob/master/package.json#L35-L37 it says

```json
"peerDependencies": {
    "@types/node": ">=14 <21"
  },
```

but now [Node.js v22 is long-term support (LTS)](https://nodejs.org/)

**Comment by oddball** [comment]
Weird of the bot to close this as "not planned".  Not like it is avoidable

**Comment by spiatrenka** [comment]
> Weird of the bot to close this as "not planned". Not like it is avoidable

@oddball, you are welcome to create a PR for the issue, if you think it's could be useful. 🙌
