### ISSUE TITLE
Regarding PDF File Contract Sign

### ISSUE THREAD

**Issue by rajmantechnology** [anyfin/bankid#9]
Dear Sir/Mam,

I am using this code authentication for personal number and its is working fine in test net.

Code:
const BankId = require("bankid");
 
const bankid = new BankId();
const pno = "YYYYMMDD-XXXX";
const message = "some message displayed to the user to sign";
 
bankid
  .sign("127.0.0.1", pno, message)
  .then(res => {
    const timer = setInterval(() => {
      const done = () => clearInterval(timer);
 
      bankid
        .collect(res.orderRef)
        .then(res => {
          if (res.status === "complete") {
            console.log(res.completionData);
            done();
          } else if (res.status === "failed") {
            throw new Error(res.hintCode);
          }
        })
        .catch(err => {
          console.error(err);
          done();
        });
    }, 1000);
  })
  .catch(console.error);
But Now i  Want to implement the upload file in pdf format and check it is correct or not though bank id app.

I am using this code in nodes.js. So please tell me the  solution . Because i am trying for a month but not got any solution. 

Thanks

**Comment by insanesvk** [comment]
What kind of PDF are you sending? Do you have /Filter and /SubFilter fields in the PDF?

I suggest you read [this](https://www.adobe.com/devnet-docs/acrobatetk/tools/DigSig/Acrobat_DigitalSignatures_in_PDF.pdf) paper by Adobe.

And since this seems not to be a problem with this package, but your implementation, I suggest asking on StackOverflow.

**Comment by rajmantechnology** [comment]
Hey insanesvk,

We are using simple pdf file like A4 size paper.

**Comment by kimpers** [comment]
Closing this issue because it's been inactive for a very long time. Feel free to open a new one if you are having any issues.
